# Generated by Django 4.2.1 on 2023-07-01 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SideBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('tpye', models.IntegerField(choices=[(1, 'HTML'), (0, '最新文章'), (2, '最热文章'), (3, '最热评论')], default=1, verbose_name='展示类型')),
                ('content', models.CharField(blank=True, max_length=400, verbose_name='内容')),
                ('status', models.IntegerField(choices=[(1, '显示'), (0, '隐藏')], default=1, verbose_name='显示状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '侧边栏',
                'verbose_name_plural': '侧边栏',
                'db_table': 'df_sidebar',
            },
        ),
    ]
